# Use root/example as user/password credentials
version: '3.1'

services:

  snippetdb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "mysqldata:/var/lib/mysql"

  snippetadminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
volumes:
  mysqldata: